### ISSUE TITLE
Come Back To-Do List

### ISSUE THREAD

**Issue by ZhenboYan** [esnet/sense-rtmon#20]
- [ ] Curl API and data source keys.
- [ ] Auto add the keys to configuration file.
- [ ] Paths to encryption certificates from Nginx automatically updates.
- [ ] Clean up the unused code in start and install process.
